let nickname = prompt("이름 또는 별명을 입력해주세요")
let drink = prompt("원하는 음료를 입력해주세요")
let number = prompt("원하는 수량을 입력해주세요")
console.log("고객님의 성함은:", nickname)
console.log("고객님이 입력해주신 음료:", drink)
console.log("고객님이 입력해주신 주문수량:", number)

let nickname2 = prompt("이름 또는 별명을 입력해주세요")
let activity = prompt("수행한 운동 종류를 입력해주세요")
let worktime = prompt("운동 시간을 입력해주세요")
console.log("고객님의 성함은:", nickname2)
console.log("운동종류:", activity)
console.log("운동시간:", worktime)
console.log("소모 칼로리:", worktime * 7)
